
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: true,
    base: 'https://intelehealth.mpower-social.com',
    baseURL: 'https://intelehealth.mpower-social.com/openmrs/ws/rest/v1',
    baseURLCoreApp: 'https://intelehealth.mpower-social.com/openmrs/coreapps/diagnoses',
    baseURLLegacy: 'https://intelehealth.mpower-social.com/openmrs/',
    mindmapURL: 'https://intelehealth.mpower-social.com:3004/api',
    notificationURL: 'https://intelehealth.mpower-social.com:3004/notification',
    socketURL: 'https://intelehealth.mpower-social.com:3004',
    captchaSiteKey: '6LdbXvApAAAAANFjXjgOQnaX7ESR2IBPIOO9KpvS',
    firebase: {
        apiKey: 'AIzaSyDCC1JLFTVhM5smLy5BTn96dhiOj_gSUWQ',
        authDomain: 'intelhealth-mpower.firebaseapp.com',
        projectId: 'intelhealth-mpower',
        storageBucket: 'intelhealth-mpower.appspot.com',
        messagingSenderId: '971382487208',
        appId: '1:971382487208:web:13f83dac2ff14f54bdaa9d',
    },
    webrtcSdkServerUrl: 'wss://intelehealth.mpower-social.com:9090',
    webrtcTokenServerUrl: 'https://intelehealth.mpower-social.com:3030',
    siteKey: '6Lf_UPEpAAAAAJesudYovsIWUXdpCtCGUtphyqIZ',
    externalPrescriptionCred: 'undefined',
    vapidPublicKey: 'BACBe2a-6cpm7RESlWn4Ln1ofnSQxbeedmg5kuPq9CqJ8hX22cfFUGaU5R5E9bM8w-7M_NDWBPOz3zVzfKP0mm4',
    authGatwayURL: 'https://intelehealth.mpower-social.com:3030/v2/',
    showCaptcha: false,
    recordsPerPage: 1000
  };
